# This workflow will install Python dependencies, run tests and lint
# with a single version of Python For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: FFCX CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (non-Python, Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libgraphviz-dev pkg-config
      - name: Install dependencies (non-Python, macOS)
        if: runner.os == 'macOS'
        run: brew install graphviz pkg-config
      - name: Install dependencies (Python)
        run: |
          pip install --upgrade pip
          pip install pygraphviz wheel
          pip install git+https://github.com/chrisrichardson/fiat.git --user
          pip install git+https://github.com/chrisrichardson/ufl.git --user
      - name: Lint with flake8
        run: |
          pip install flake8 setuptools_scm
          flake8 --statistics ffcx/ test/
      - name: Check documentation style
        run: |
          pip install pydocstyle
          pydocstyle .
      - name: Install ffcx
        run: |
          pip install setuptools_scm
          pip install .
          ls -lR ~/.local/lib/python3.8/site-packages/ffcx
      - name: Run units tests
        run: |
          pip install pytest pytest-xdist
          pytest -n auto test
      - name: Runs demos
        run: |
          ffcx demo/*.ufl
